# Generated by Django 4.1.3 on 2022-11-24 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_course_created_at_alter_course_deleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseteacher',
            old_name='courses',
            new_name='course',
        ),
    ]
